ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "userType" TEXT NOT NULL DEFAULT 'staff';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "position" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "dept" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "subDept" TEXT;
